version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  verbosity: minimal
before_package:
- cmd: echo %APPVEYOR_BUILD_VERSION% > version

artifacts:
- path: '\Launcher\bin\Release\*'
- path: '\version'